const translations = {
  "Translate": {
    Afrikaans: "Vertaal",
    Arabic: "ترجمة",
    Armenian: "Թարգմանել",
    Azerbaijani: "Tərcümə et",
    Belarusian: "Перакласці",
    Bosnian: "Prevedi",
    Bulgarian: "Преведи",
    Catalan: "Traduir",
    Chinese: "翻译",
    Croatian: "Prevedi",
    Czech: "Přeložit",
    Danish: "Oversæt",
    Dutch: "Vertaal",
    English: "Translate",
    Estonian: "Tõlgi",
    Finnish: "Käännä",
    French: "Traduire",
    Galician: "Traducir",
    German: "Übersetzen",
    Greek: "Μετάφραση",
    Hebrew: "תרגם",
    Hindi: "अनुवाद करें",
    Hungarian: "Fordítás",
    Icelandic: "Þýða",
    Indonesian: "Terjemahkan",
    Italian: "Traduci",
    Japanese: "翻译",
    Kannada: "ಅನುವಾದಿಸಿ",
    Kazakh: "Аудару",
    Korean: "번역",
    Latvian: "Tulko",
    Lithuanian: "Išversti",
    Macedonian: "Преведи",
    Malay: "Terjemah",
    Marathi: "भाषांतर करा",
    Maori: "Whakamāoritia",
    Nepali: "अनुवाद गर्नुहोस्",
    Norwegian: "Oversett",
    Persian: "ترجمه",
    Polish: "Przetłumacz",
    Portuguese: "Traduzir",
    Romanian: "Tradu",
    Russian: "Перевести",
    Serbian: "Преведи",
    Slovak: "Preložiť",
    Slovenian: "Prevedi",
    Spanish: "Traducir",
    Swahili: "Tafsiri",
    Swedish: "Översæt",
    Tagalog: "Isalin",
    Tamil: "மொழிபெயர்",
    Thai: "แปล",
    Turkish: "Çevir",
    Ukrainian: "Перекласти",
    Urdu: "ترجم کریں",
    Vietnamese: "Dịch",
    Welsh: "Cyfieithu"
  },
  "Start recording": {
    Afrikaans: "Begin opname",
    Arabic: "ابدأ التسجيل",
    Armenian: "Սկսել գրառում",
    Azerbaijani: "Yazmağa başla",
    Belarusian: "Пачаць запіс",
    Bosnian: "Počni snimanje",
    Bulgarian: "Започни запис",
    Catalan: "Inicia gravació",
    Chinese: "开始录音",
    Croatian: "Započni snimanje",
    Czech: "Začni nahrávat",
    Danish: "Start optagelse",
    Dutch: "Begin met opnemen",
    English: "Start recording",
    Estonian: "Alusta salvestamist",
    Finnish: "Aloita nauhoitus",
    French: "Commencez l'enregistrement",
    Galician: "Comeza gravar",
    German: "Aufnahme starten",
    Greek: "Έναρξη εγγραφής",
    Hebrew: "התחל הקלטה",
    Hindi: "रिकॉर्डिंग शुरू करें",
    Hungarian: "Felvétel indítása",
    Icelandic: "Byrja upptöku",
    Indonesian: "Mulai merekam",
    Italian: "Inizia a registrare",
    Japanese: "録音を開始",
    Kannada: "ರೆಕಾರ್ಡಿಂಗ್ ಪ್ರಾರಂಭಿಸಿ",
    Kazakh: "Жазуды бастаңыз",
    Korean: "녹음을 시작하세요",
    Latvian: "Sāc ierakstīšanu",
    Lithuanian: "Pradėti įrašymą",
    Macedonian: "Започни снимање",
    Malay: "Mulakan rakaman",
    Marathi: "रेकॉर्डिंग सुरू करा",
    Maori: "Tīmata te reo",
    Nepali: "रेकर्डिङ सुरु गर्नुहोस्",
    Norwegian: "Start opptak",
    Persian: "ضبط صدا را شروع کن",
    Polish: "Rozpocznij nagrywanie",
    Portuguese: "Iniciar gravação",
    Romanian: "Pornește înregistrarea",
    Russian: "Начать запись",
    Serbian: "Почни снимање",
    Slovak: "Začni nahrávať",
    Slovenian: "Začni snemati",
    Spanish: "Iniciar grabación",
    Swahili: "Anza kurekodi",
    Swedish: "Börja spela in",
    Tagalog: "Simulan ang pagrekord",
    Tamil: "ஒலிப்பதிவு தொடங்கவும்",
    Thai: "เริ่มบันทึกเสียง",
    Turkish: "Kaydı başlat",
    Ukrainian: "Почати запис",
    Urdu: "ریکارڈنگ شروع کریں",
    Vietnamese: "Bắt đầu ghi âm",
    Welsh: "Dechrau cofnodi"
  },

  "Listening": {
    Afrikaans: "Luister",
    Arabic: "جاري الاستماع",
    Armenian: "Լսում եմ",
    Azerbaijani: "Dinləyir",
    Belarusian: "Слухае",
    Bosnian: "Slušanje",
    Bulgarian: "Слушане",
    Catalan: "Escoltant",
    Chinese: "正在聆听",
    Croatian: "Slušanje",
    Czech: "Poslouchá",
    Danish: "Lytter",
    Dutch: "Luisteren",
    English: "Listening",
    Estonian: "Kuulamine",
    Finnish: "Kuuntelee",
    French: "En écoute",
    Galician: "Escoitando",
    German: "Zuhören",
    Greek: "Ακούει",
    Hebrew: "מאזין",
    Hindi: "सुन रहा है",
    Hungarian: "Figyel",
    Icelandic: "Hlusta",
    Indonesian: "Mendengarkan",
    Italian: "Ascoltando",
    Japanese: "聞いています",
    Kannada: "ಕೇಳುತ್ತಿದೆ",
    Kazakh: "Тыңдап жатыр",
    Korean: "듣는 중",
    Latvian: "Klausās",
    Lithuanian: "Klausosi",
    Macedonian: "Слушање",
    Malay: "Mendengar",
    Marathi: "ऐकत आहे",
    Maori: "Kei te rongo",
    Nepali: "सुनिरहेको छ",
    Norwegian: "Lytter",
    Persian: "در حال گوش دادن",
    Polish: "Słuchanie",
    Portuguese: "Ouvindo",
    Romanian: "Ascultând",
    Russian: "Слушает",
    Serbian: "Слушање",
    Slovak: "Počuje",
    Slovenian: "Poslušanje",
    Spanish: "Escuchando",
    Swahili: "Inasikiliza",
    Swedish: "Lyssnar",
    Tagalog: "Nakikinig",
    Tamil: "கேட்கிறேன்",
    Thai: "กำลังฟัง",
    Turkish: "Dinliyor",
    Ukrainian: "Слухає",
    Urdu: "سن رہا ہے",
    Vietnamese: "Đang nghe",
    Welsh: "Wrando"
  },

  "One moment": {
    Afrikaans: "Een oomblik",
    Arabic: "لحظة واحدة",
    Armenian: "Մի պահ",
    Azerbaijani: "Bir dəqiqə",
    Belarusian: "Хвіліна",
    Bosnian: "Jedan trenutak",
    Bulgarian: "Момент",
    Catalan: "Un moment",
    Chinese: "请稍候",
    Croatian: "Jedan trenutak",
    Czech: "Chvilku",
    Danish: "Et øjeblik",
    Dutch: "Een moment",
    English: "One moment",
    Estonian: "Üks hetk",
    Finnish: "Hetki",
    French: "Un instant",
    Galician: "Un momento",
    German: "Einen Moment",
    Greek: "Μια στιγμή",
    Hebrew: "רגע",
    Hindi: "प्रतीक्षा",
    Hungarian: "Egy pillanat",
    Icelandic: "Ein augnablik",
    Indonesian: "Sebentar",
    Italian: "Un attimo",
    Japanese: "ちょっと待って",
    Kannada: "ಒಂದು ಕ್ಷಣ",
    Kazakh: "Бір сәт",
    Korean: "잠시만요",
    Latvian: "Vienu mirkli",
    Lithuanian: "Vieną akimirką",
    Macedonian: "Еден момент",
    Malay: "Sebentar",
    Marathi: "एक क्षण",
    Maori: "Kotahi wā",
    Nepali: "एक छिन",
    Norwegian: "Ett øyeblikk",
    Persian: "یک لحظه",
    Polish: "Chwileczkę",
    Portuguese: "Um momento",
    Romanian: "Un moment",
    Russian: "Минуточку",
    Serbian: "Један тренутак",
    Slovak: "Moment",
    Slovenian: "En trenutek",
    Spanish: "Un momento",
    Swahili: "Wakati mmoja",
    Swedish: "Ett ögonblick",
    Tagalog: "Sandali lang",
    Tamil: "ஒரு நிமிடம்",
    Thai: "สักครู่",
    Turkish: "Bir dakika",
    Ukrainian: "Момент",
    Urdu: "ایک لمحہ",
    Vietnamese: "Một chút",
    Welsh: "Amser bach"
  },

  "Replay": {
    Afrikaans: "Speel weer",
    Arabic: "إعادة تشغيل",
    Armenian: "Կրկնել",
    Azerbaijani: "Təkrar oynat",
    Belarusian: "Паўтарыць",
    Bosnian: "Ponavljanje",
    Bulgarian: "Повтори",
    Catalan: "Reproduir de nou",
    Chinese: "重放",
    Croatian: "Pusti ponovno",
    Czech: "Přehrát znovu",
    Danish: "Afspil igen",
    Dutch: "Opnieuw afspelen",
    English: "Replay",
    Estonian: "Mängi uuesti",
    Finnish: "Toista",
    French: "Rejouer",
    Galician: "Reproducir de novo",
    German: "Erneut abspielen",
    Greek: "Ξαναπαίξτε",
    Hebrew: "נגן מחדש",
    Hindi: "फिर से चलाएं",
    Hungarian: "Újrajátszás",
    Icelandic: "Endurspila",
    Indonesian: "Putar ulang",
    Italian: "Riproduci nuovamente",
    Japanese: "再生",
    Kannada: "ಮರುಹಿಡಿ",
    Kazakh: "Қайта ойнату",
    Korean: "다시 재생",
    Latvian: "Atkārtot",
    Lithuanian: "Peržiūrėti iš naujo",
    Macedonian: "Повтори",
    Malay: "Main semula",
    Marathi: "पुन्हा प्ले करा",
    Maori: "Tāruatia anō",
    Nepali: "फेरि चलाउनुहोस्",
    Norwegian: "Spill av igjen",
    Persian: "پخش مجدد",
    Polish: "Odtwórz ponownie",
    Portuguese: "Reproduzir novamente",
    Romanian: "Redă din nou",
    Russian: "Воспроизвести снова",
    Serbian: "Поново пусти",
    Slovak: "Prehrať znovu",
    Slovenian: "Predvajaj ponovno",
    Spanish: "Reproducir de nuevo",
    Swahili: "Chezesha tena",
    Swedish: "Spela upp igen",
    Tagalog: "Ulitin",
    Tamil: "மீண்டும் இயக்கவும்",
    Thai: "เล่นซ้ำ",
    Turkish: "Tekrar Oynat",
    Ukrainian: "Програти знову",
    Urdu: "دوبارہ چلائیں",
    Vietnamese: "Phát lại",
    Welsh: "Ailadrodd"
  }
};

export function getHomeData() {
  return translations;
}