const languages = [
  { name: "Afrikaans", code: "af", flag: "🇿🇦", link: "https://tl-test-storage.nyc3.cdn.digitaloceanspaces.com/cipher/za.jpg" },
  { name: "Arabic", code: "ar", flag: "🇸🇦", link: "https://tl-test-storage.nyc3.cdn.digitaloceanspaces.com/cipher/sa.jpg" },
  { name: "Armenian", code: "hy", flag: "🇦🇲", link: "https://tl-test-storage.nyc3.cdn.digitaloceanspaces.com/cipher/am.jpg" },
  { name: "Azerbaijani", code: "az", flag: "🇦🇿", link: "https://tl-test-storage.nyc3.cdn.digitaloceanspaces.com/cipher/az.jpg" },
  { name: "Belarusian", code: "be", flag: "🇧🇾", link: "https://tl-test-storage.nyc3.cdn.digitaloceanspaces.com/cipher/by.jpg" },
  { name: "Bosnian", code: "bs", flag: "🇧🇦", link: "https://tl-test-storage.nyc3.cdn.digitaloceanspaces.com/cipher/ba.jpg" },
  { name: "Bulgarian", code: "bg", flag: "🇧🇬", link: "https://tl-test-storage.nyc3.cdn.digitaloceanspaces.com/cipher/bg.jpg" },
  { name: "Catalan", code: "ca", flag: "🇪🇸", link: "https://tl-test-storage.nyc3.cdn.digitaloceanspaces.com/cipher/catalan.jpg" },
  { name: "Chinese", code: "zh", flag: "🇨🇳", link: "https://tl-test-storage.nyc3.cdn.digitaloceanspaces.com/cipher/cn.jpg" },
  { name: "Croatian", code: "hr", flag: "🇭🇷", link: "https://tl-test-storage.nyc3.cdn.digitaloceanspaces.com/cipher/hr.jpg" },
  { name: "Czech", code: "cs", flag: "🇨🇿", link: "https://tl-test-storage.nyc3.cdn.digitaloceanspaces.com/cipher/cz.jpg" },
  { name: "Danish", code: "da", flag: "🇩🇰", link: "https://tl-test-storage.nyc3.cdn.digitaloceanspaces.com/cipher/dk.jpg" },
  { name: "Dutch", code: "nl", flag: "🇳🇱", link: "https://tl-test-storage.nyc3.cdn.digitaloceanspaces.com/cipher/nl.jpg" },
  { name: "English", code: "en", flag: "🇬🇧", link: "https://tl-test-storage.nyc3.cdn.digitaloceanspaces.com/cipher/gb.jpg" },
  { name: "Estonian", code: "et", flag: "🇪🇪", link: "https://tl-test-storage.nyc3.cdn.digitaloceanspaces.com/cipher/ee.jpg" },
  { name: "Finnish", code: "fi", flag: "🇫🇮", link: "https://tl-test-storage.nyc3.cdn.digitaloceanspaces.com/cipher/fi.jpg" },
  { name: "French", code: "fr", flag: "🇫🇷", link: "https://tl-test-storage.nyc3.cdn.digitaloceanspaces.com/cipher/fr.jpg" },
  { name: "Galician", code: "gl", flag: "🇪🇸", link: "https://tl-test-storage.nyc3.cdn.digitaloceanspaces.com/cipher/galicia.jpg" },
  { name: "German", code: "de", flag: "🇩🇪", link: "https://tl-test-storage.nyc3.cdn.digitaloceanspaces.com/cipher/de.jpg" },
  { name: "Greek", code: "el", flag: "🇬🇷", link: "https://tl-test-storage.nyc3.cdn.digitaloceanspaces.com/cipher/gr.jpg" },
  { name: "Hebrew", code: "he", flag: "🇮🇱", link: "https://tl-test-storage.nyc3.cdn.digitaloceanspaces.com/cipher/il.jpg" },
  { name: "Hindi", code: "hi", flag: "🇮🇳", link: "https://tl-test-storage.nyc3.cdn.digitaloceanspaces.com/cipher/in.jpg" },
  { name: "Hungarian", code: "hu", flag: "🇭🇺", link: "https://tl-test-storage.nyc3.cdn.digitaloceanspaces.com/cipher/hu.jpg" },
  { name: "Icelandic", code: "is", flag: "🇮🇸", link: "https://tl-test-storage.nyc3.cdn.digitaloceanspaces.com/cipher/is.jpg" },
  { name: "Indonesian", code: "id", flag: "🇮🇩", link: "https://tl-test-storage.nyc3.cdn.digitaloceanspaces.com/cipher/id.jpg" },
  { name: "Italian", code: "it", flag: "🇮🇹", link: "https://tl-test-storage.nyc3.cdn.digitaloceanspaces.com/cipher/it.jpg" },
  { name: "Japanese", code: "ja", flag: "🇯🇵", link: "https://tl-test-storage.nyc3.cdn.digitaloceanspaces.com/cipher/jp.jpg" },
  { name: "Kannada", code: "kn", flag: "🇮🇳", link: "https://tl-test-storage.nyc3.cdn.digitaloceanspaces.com/cipher/kannada.jpg" },
  { name: "Kazakh", code: "kk", flag: "🇰🇿", link: "https://tl-test-storage.nyc3.cdn.digitaloceanspaces.com/cipher/kz.jpg" },
  { name: "Korean", code: "ko", flag: "🇰🇷", link: "https://tl-test-storage.nyc3.cdn.digitaloceanspaces.com/cipher/kr.jpg" },
  { name: "Latvian", code: "lv", flag: "🇱🇻", link: "https://tl-test-storage.nyc3.cdn.digitaloceanspaces.com/cipher/lv.jpg" },
  { name: "Lithuanian", code: "lt", flag: "🇱🇹", link: "https://tl-test-storage.nyc3.cdn.digitaloceanspaces.com/cipher/lt.jpg" },
  { name: "Macedonian", code: "mk", flag: "🇲🇰", link: "https://tl-test-storage.nyc3.cdn.digitaloceanspaces.com/cipher/mk.jpg" },
  { name: "Malay", code: "ms", flag: "🇲🇾", link: "https://tl-test-storage.nyc3.cdn.digitaloceanspaces.com/cipher/my.jpg" },
  { name: "Marathi", code: "mr", flag: "🇮🇳", link: "https://tl-test-storage.nyc3.cdn.digitaloceanspaces.com/cipher/marathi.jpg" },
  { name: "Maori", code: "mi", flag: "🇳🇿", link: "https://tl-test-storage.nyc3.cdn.digitaloceanspaces.com/cipher/maori.jpg" },
  { name: "Nepali", code: "ne", flag: "🇳🇵", link: "https://tl-test-storage.nyc3.cdn.digitaloceanspaces.com/cipher/np.jpg" },
  { name: "Norwegian", code: "no", flag: "🇳🇴", link: "https://tl-test-storage.nyc3.cdn.digitaloceanspaces.com/cipher/no.jpg" },
  { name: "Persian", code: "fa", flag: "🇮🇷", link: "https://tl-test-storage.nyc3.cdn.digitaloceanspaces.com/cipher/ir.jpg" },
  { name: "Polish", code: "pl", flag: "🇵🇱", link: "https://tl-test-storage.nyc3.cdn.digitaloceanspaces.com/cipher/pl.jpg" },
  { name: "Portuguese", code: "pt", flag: "🇵🇹", link: "https://tl-test-storage.nyc3.cdn.digitaloceanspaces.com/cipher/pt.jpg" },
  { name: "Romanian", code: "ro", flag: "🇷🇴", link: "https://tl-test-storage.nyc3.cdn.digitaloceanspaces.com/cipher/ro.jpg" },
  { name: "Russian", code: "ru", flag: "🇷🇺", link: "https://tl-test-storage.nyc3.cdn.digitaloceanspaces.com/cipher/ru.jpg" },
  { name: "Serbian", code: "sr", flag: "🇷🇸", link: "https://tl-test-storage.nyc3.cdn.digitaloceanspaces.com/cipher/rs.jpg" },
  { name: "Slovak", code: "sk", flag: "🇸🇰", link: "https://tl-test-storage.nyc3.cdn.digitaloceanspaces.com/cipher/sk.jpg" },
  { name: "Slovenian", code: "sl", flag: "🇸🇮", link: "https://tl-test-storage.nyc3.cdn.digitaloceanspaces.com/cipher/si.jpg" },
  { name: "Spanish", code: "es", flag: "🇪🇸", link: "https://tl-test-storage.nyc3.cdn.digitaloceanspaces.com/cipher/es.jpg" },
  { name: "Swahili", code: "sw", flag: "🇰🇪", link: "https://tl-test-storage.nyc3.cdn.digitaloceanspaces.com/cipher/swahili.jpg" },
  { name: "Swedish", code: "sv", flag: "🇸🇪", link: "https://tl-test-storage.nyc3.cdn.digitaloceanspaces.com/cipher/se.jpg" },
  { name: "Tagalog", code: "tl", flag: "🇵🇭", link: "https://tl-test-storage.nyc3.cdn.digitaloceanspaces.com/cipher/tagalog.jpg" },
  { name: "Tamil", code: "ta", flag: "🇮🇳", link: "https://tl-test-storage.nyc3.cdn.digitaloceanspaces.com/cipher/tamil.jpg" },
  { name: "Thai", code: "th", flag: "🇹🇭", link: "https://tl-test-storage.nyc3.cdn.digitaloceanspaces.com/cipher/th.jpg" },
  { name: "Turkish", code: "tr", flag: "🇹🇷", link: "https://tl-test-storage.nyc3.cdn.digitaloceanspaces.com/cipher/tr.jpg" },
  { name: "Ukrainian", code: "uk", flag: "🇺🇦", link: "https://tl-test-storage.nyc3.cdn.digitaloceanspaces.com/cipher/ua.jpg" },
  { name: "Urdu", code: "ur", flag: "🇵🇰", link: "https://tl-test-storage.nyc3.cdn.digitaloceanspaces.com/cipher/pk.jpg" },
  { name: "Vietnamese", code: "vi", flag: "🇻🇳", link: "https://tl-test-storage.nyc3.cdn.digitaloceanspaces.com/cipher/vn.jpg" },
  { name: "Welsh", code: "cy", flag: "🏴󠁧󠁢󠁷󠁬󠁳󠁿", link: "https://tl-test-storage.nyc3.cdn.digitaloceanspaces.com/cipher/gb-wls.jpg" },
];

export function getLanguages() {
  return languages;
}
